### PR TITLE
Division by zero in a virtual method

### PR DESCRIPTION
**Pull request by andrewt0301**
Examples that demonstrates that Clang-Tidy cannot find DIVISION BY ZERO in a virtual method.

### CODE REVIEW

**Comment by yegor256** [comment]
@andrewt0301 can you make it simpler? Now you use the array in the `main` function, which is a bit confusing. Can you just show ONE case where the bug exists, but Clang doesn't see it?

**Comment by andrewt0301** [comment]
> @andrewt0301 can you make it simpler? Now you use the array in the `main` function, which is a bit confusing. Can you just show ONE case where the bug exists, but Clang doesn't see it?

Done. Array is not needed.

**Comment by andrewt0301** [comment]
Added one more comment. Further simplification is not possible.

**Comment by yegor256** [comment]
@andrewt0301 thanks!

**Pull request merged**
